### ISSUE TITLE
Need way to declare values as safe without using closure libraries

### ISSUE THREAD

**Issue by wyattallen** [Polymer/polymer-resin#5]
PolyGerrit doesn't use closure libraries, but the documentation doesn't show how to declare values as safe in JS without using the `goog.http.*` types.

**Comment by mikesamuel** [comment]
> without using the goog.http.* types.

`s/http/html/` ?

----

I was planning on adding an `isSafeInContext` hook for

* [Trusted types interop](https://github.com/WICG/trusted-types)
* [React hardening](https://gist.github.com/mikesamuel/094d3fe4b1b2f702f543fa0c263ca8ff#suggestion-hybrid-of-before-desugar-and-mutate-reconciler)

That should allow plugging in a non-closure implementation of trusted types.
Would that be sufficient for you?

**Comment by wyattallen** [comment]
> Would that be sufficient for you?

That certainly sounds sufficient!

> s/http/html/ ?

Yes, oops. :-)

**Comment by mikesamuel** [comment]
Closing.  [safeTypesBridge](https://github.com/Polymer/polymer-resin/blob/master/getting-started.md#-safetypesbridge-mybridgefn-) has landed.
